AHUB API:ERROR [Nov-23-2022 16:25:58] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:25:58] Error creating Patron : {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}  ðŸ˜ 
AHUB API:ERROR [Nov-23-2022 16:27:36] Login failed. Please try again later.: Error: Invalid login credentials
AHUB API:ERROR [Nov-23-2022 16:31:04] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:31:12] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:31:17] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:31:19] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:43:47] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:43:47] Error creating Patron : {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}  ðŸ˜ 
AHUB API:ERROR [Nov-23-2022 16:54:35] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:56:39] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:56:43] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 16:56:44] Error generating OTP: {"clientVersion":"4.6.1"}
AHUB API:ERROR [Nov-23-2022 18:19:29] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 18:20:58] OTP Error: {"message":"getaddrinfo EAI_AGAIN us.sms.api.sinch.com","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN us.sms.api.sinch.com\n    at Function.AxiosError.from (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:725:14)\n    at RedirectableRequest.handleRequestError (E:\\Projects\\servers\\ahub-api\\node_modules\\axios\\dist\\node\\axios.cjs:2467:25)\n    at RedirectableRequest.emit (node:events:520:28)\n    at ClientRequest.eventHandlers.<computed> (E:\\Projects\\servers\\ahub-api\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:520:28)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:520:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","Authorization":"Bearer d0f03e6c80df4e97b74feda4ac1d092f","User-Agent":"axios/1.1.3","Content-Length":"82","Accept-Encoding":"gzip, deflate, br"},"method":"post","url":"https://us.sms.api.sinch.com/xms/v1/e0c81087c4a5433394bf1607b2c5a86a/batches","data":"{\"from\":\"+12064743920\",\"to\":[\"+2348034074748\"],\"body\":\"your OTP [object Promise]\"}"},"code":"EAI_AGAIN","status":null}
AHUB API:ERROR [Nov-23-2022 18:22:07] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:37] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:41] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:43] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:45] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:46] OTP Error
AHUB API:ERROR [Nov-23-2022 18:35:48] Error generating OTP: {"code":"P2034","clientVersion":"4.6.1","meta":{}}
AHUB API:ERROR [Nov-23-2022 18:40:14] OTP Error
AHUB API:ERROR [Nov-23-2022 18:40:19] OTP Error
AHUB API:ERROR [Nov-23-2022 18:40:22] OTP Error
AHUB API:ERROR [Nov-23-2022 19:03:51] OTP Error
AHUB API:ERROR [Nov-23-2022 19:03:56] OTP Error
AHUB API:ERROR [Nov-23-2022 19:04:06] Error generating OTP: {"code":"P2034","clientVersion":"4.6.1","meta":{}}
AHUB API:ERROR [Nov-23-2022 23:00:54] Login failed. Please try again later.: Error: 
Invalid `prisma_1.Prisma.user.findUnique()` invocation in
E:\Projects\servers\ahub-api\dist\Controllers\AuthController.js:30:61

  27 try {
  28     //const data = await Cache.baseCache('login', async () => {
  29     Libs_1.Logger.info('Signing In.....');
â†’ 30     const user = yield prisma_1.Prisma.user.findUnique(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)" } })
AHUB API:ERROR [Nov-23-2022 23:01:06] Login failed. Please try again later.: Error: 
Invalid `prisma_1.Prisma.user.findUnique()` invocation in
E:\Projects\servers\ahub-api\dist\Controllers\AuthController.js:30:61

  27 try {
  28     //const data = await Cache.baseCache('login', async () => {
  29     Libs_1.Logger.info('Signing In.....');
â†’ 30     const user = yield prisma_1.Prisma.user.findUnique(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)" } })
AHUB API:ERROR [Nov-23-2022 23:01:12] Login failed. Please try again later.: Error: 
Invalid `prisma_1.Prisma.user.findUnique()` invocation in
E:\Projects\servers\ahub-api\dist\Controllers\AuthController.js:30:61

  27 try {
  28     //const data = await Cache.baseCache('login', async () => {
  29     Libs_1.Logger.info('Signing In.....');
â†’ 30     const user = yield prisma_1.Prisma.user.findUnique(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. (os error 11002)" } })
AHUB API:ERROR [Nov-24-2022 20:55:48] Cache Error: Error: The client is closed
AHUB API:ERROR [Nov-24-2022 20:56:43]  Error: The client is closed
AHUB API:ERROR [Nov-24-2022 20:57:10] Cache Error: The client is closed
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:41] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:42] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:43] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:43] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:44] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:44] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:45] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:45] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:46] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:46] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:47] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:47] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:48] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:48] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:49] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:49] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:50] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:51] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:51] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:52] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:52] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:53] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:53] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:54] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:54] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 20:57:55] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:13:59] Error connection to redis: Error: read ECONNRESET
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:01] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:02] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:03] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:04] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:09] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-24-2022 21:14:15] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-24-2022 21:14:18] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:18] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:19] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:19] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:20] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:20] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:21] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:22] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:14:27] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-24-2022 21:22:12] Error connection to redis: Error: read ECONNRESET
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: connect ECONNABORTED 54.92.223.199:10612
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:16] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:17] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:17] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:17] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:18] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:18] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:23] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:31] Error connection to redis: Error: Connection timeout
AHUB API:ERROR [Nov-24-2022 21:22:35] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:36] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:36] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:37] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:38] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:38] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:39] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:41] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:41] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:42] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:43] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:43] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:44] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:44] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:45] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:45] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:46] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:46] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:47] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:47] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:48] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:48] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:49] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:49] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:50] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:50] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:51] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:52] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:52] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:53] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:53] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:56] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:56] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:57] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:57] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:58] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:58] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:59] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:22:59] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:00] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:00] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:01] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:02] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:02] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:03] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:03] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:04] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:04] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:05] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:06] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:06] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:07] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:07] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:08] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:08] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:09] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:09] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:10] Error connection to redis: Error: getaddrinfo ENOTFOUND redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
AHUB API:ERROR [Nov-24-2022 21:23:11] Error connection to redis: Error: getaddrinfo EAI_AGAIN redis-10612.c93.us-east-1-3.ec2.cloud.redislabs.com
